
FROM node:16
ARG REACT_APP_ENVIRONMENT=production

ARG REACT_APP_ALCHEMY_API_KEY=
ARG REACT_APP_ALCHEMY_URL=
ARG REACT_APP_EXAMPLE_WALLET=

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

# Build the built version
RUN npm run build

RUN yarn global add serve

CMD ["serve","-s","build"]